const dataFonts = {
  "Earth": "Windows",
  "Ume Mincho S3": "Linux",
  "Ume P Gothic S5": "Linux",
  "Nimbus Sans Narrow": "Linux",
  "MotoyaG04Gothic": "Chrome OS",
  "Westwood LET": "Windows",
  "Latin Modern Mono Caps": "Linux",
  "Comic Sans MS Gras": "Mac OS",
  "Ume Gothic C5": "Linux",
  "12x10": "Windows",
  "Ume Gothic O5": "Linux",
  "Tlwg Mono": "Linux",
  "ITF Devanagari": "Mac OS",
  "Ume P Mincho": "Linux",
  "W": "Windows",
  "Bickham Script Pro Regular": "Windows",
  "OldDreadfulNo7 BT": "Windows",
  "36p Kana": "Mac OS",
  "Georgia Italique": "Mac OS",
  "Ostrich Sans Heavy": "Windows",
  "Arial Narrow Italique": "Mac OS",
  "Ume UI Gothic O5": "Linux",
  "IV50": "Windows",
  "Laksaman": "Linux",
  "Hiragino Sans": "Mac OS",
  "Charlie": "Windows",
  "Gabo Drive": "Windows",
  "IV25": "Windows",
  "Nuosu SIL": "Linux",
  "NewJumja": "Windows",
  "Ki": "Windows",
  "Tiranti Solid LET": "Windows",
  "Verdana Gras": "Mac OS",
  "Phosphate": "Mac OS",
  "TSCu": "Linux",
  "Noto Sans Emoji": "Chrome OS",
  "TAMu": "Linux",
  "MisterEarl BT": "Windows",
  "PakType Naqsh": "Linux",
  "Ume Gothic": "Linux",
  "ITF Devanagari Marathi": "Mac OS",
  "Police système Courant": "Mac OS",
  "Mona Lisa Solid ITC TT": "Mac OS",
  "Thonburi Gras": "Mac OS",
  "Tlwg Typewriter": "Linux",
  "WenQuanYi Zen Hei Sharp": "Linux",
  "Bodoni 72": "Mac OS",
  "Smudger LET": "Windows",
  "P": "Windows",
  "Tahoma Gras": "Mac OS",
  "Apple Emoji couleur": "Mac OS",
  "MotoyaG04MinchoMono": "Chrome OS",
  "Mekanik LET": "Windows",
  "FixedSys": "Windows",
  "Police système Moyen": "Mac OS",
  "msam10": "Linux",
  "Helvetica Gras": "Mac OS",
  "Clarendon": "Windows",
  "HCR Batang": "Windows",
  "John Handy LET": "Windows",
  "Times Italique": "Mac OS",
  "Courier New Italique": "Mac OS",
  "Highlight LET": "Windows",
  "Police système Gras": "Mac OS",
  "Oxygen-Sans": "Linux",
  "Latin Modern Sans": "Linux",
  "Times Gras italique": "Mac OS",
  "Ume Gothic S5": "Linux",
  "Synchro LET": "Mac OS",
  "Times New Roman Gras Italique": "Mac OS",
  "Albertus Medium": "Windows",
  "Latin Modern Sans Demi Cond": "Linux",
  "Ruach LET": "Windows",
  "eufm10": "Linux",
  "Police système Léger": "Mac OS",
  "CL": "Windows",
  "Arial Gras": "Mac OS",
  "Latin Modern Mono Light": "Linux",
  "AR PL UMing TW MBE": "Linux",
  "Ume P Gothic C4": "Linux",
  "SchoolHouse Printed A": "Mac OS",
  "AR PL UMing CN": "Linux",
  "Milano LET": "Windows",
  "Latin Modern Roman Caps": "Linux",
  "PingFang TC": "Mac OS",
  "AR PL UMing TW": "Linux",
  "Enigmatic Unicode": "Windows",
  "Garamond Premr Pro": "Windows",
  "Victorian LET": "Windows",
  "Mishafi Gold": "Mac OS",
  "wasy10": "Linux",
  "Georgia Gras Italique": "Mac OS",
  "Arial Gras Italique": "Mac OS",
  "Marigold": "Windows",
  "Arial Italique": "Mac OS",
  "Latin Modern Roman Demi": "Linux",
  "Latin Modern Mono Slanted": "Linux",
  "Courier New Gras": "Mac OS",
  "MotoyaG04Mincho": "Chrome OS",
  "SchoolHouse Cursive B": "Mac OS",
  "Courier New Gras Italique": "Mac OS",
  "Bordeaux Roman Bold LET": "Mac OS",
  "Princetown LET": "Mac OS",
  "Latin Modern Mono Prop Light": "Linux",
  "Pump Demi Bold LET": "Windows",
  "Latin Modern Roman": "Linux",
  "Latin Modern Mono Prop": "Linux",
  "Ume P Gothic": "Linux",
  "AR PL UMing HK": "Linux",
  "Times New Roman Gras": "Mac OS",
  "Brush Script MT Italique": "Mac OS",
  "cursor": "Linux",
  "Arial Narrow Gras Italique": "Mac OS",
  "Ume UI Gothic": "Linux",
  "Ume P Gothic O5": "Linux",
  "Letter Gothic": "Windows",
  "Times New Roman Italique": "Mac OS",
  "Scruff LET": "Windows",
  "SAPDings": "Windows",
  "La Bamba LET": "Windows",
  "Wolf": "Windows",
  "Bradley Hand": "Mac OS",
  "Yuanti TC": "Mac OS",
  "Microsoft Yahei": "Linux",
  "msbm10": "Linux",
  "Virgo 01": "Windows",
  "Ume Gothic S4": "Linux",
  "ParkAvenue BT": "Windows",
  "Trebuchet MS Gras Italique": "Mac OS",
  "TG Pagella Math": "Linux",
  "Latin Modern Roman Dunhill": "Linux",
  "Eeyek Unicode": "Linux",
  "Blackletter686 BT": "Windows",
  "HyhwpEQ": "Windows",
  "MSung GB18030": "Chrome OS",
  "Arial Black Normal": "Mac OS",
  "SAPIcons": "Windows",
  "Ume P Mincho S3": "Linux",
  "Police système": "Mac OS",
  "One Stroke Script LET": "Windows",
  "Bell Gothic Std Light": "Windows",
  "PingFang HK": "Mac OS",
  "Ume P Gothic C5": "Linux",
  "Ro": "Windows",
  "Roman SD": "Windows",
  "Latin Modern Sans Quotation": "Linux",
  "boot": "Windows",
  "MSung B5HK": "Chrome OS",
  "Police système Italique": "Mac OS",
  "Droid Sans Devanagari": "Linux",
  "esint10": "Linux",
  "Trebuchet MS Italique": "Mac OS",
  "Odessa LET": "Windows",
  "University Roman LET": "Windows",
  "BRK": "Windows",
  "ori1Uni": "Linux",
  "Ume Mincho": "Linux",
  "Latin Modern Roman Unslanted": "Linux",
  "Calligraph421 BT": "Windows",
  "Lohit Odia": "Linux",
  "stmary10": "Linux",
  "SignPainter": "Mac OS",
  "WST": "Windows",
  "Ume P Gothic S4": "Linux",
  "HCR Dotum": "Windows",
  "pcf": "Linux",
  "Times Gras": "Mac OS",
  "Khmer OS Content": "Linux",
  "Broadway BT": "Windows",
  "Orange LET": "Windows",
  "Montserrat SemiBold": "Windows",
  "IPT": "Windows",
  "Verdana Italique": "Mac OS",
  "Staccato222 BT": "Windows",
  "Tsukushi B Round Gothic": "Mac OS",
  "HolidayPi BT": "Windows",
  "Quixley LET": "Windows",
  "Courier Gras": "Mac OS",
  "Fixed": "Linux",
  "Arial monospaced for SAP": "Windows",
  "Georgia Gras": "Mac OS",
  "Lohit Gurmukhi": "Linux",
  "Bodoni 72 Smallcaps": "Mac OS",
  "rsfs10": "Linux",
  "PingFang SC": "Mac OS",
  "Kohinoor Devanagari": "Mac OS",
  "Kievit Offc Pro": "Windows",
  "Police système Semi-gras": "Mac OS",
  "Bradley Hand Gras": "Mac OS",
  "Latin Modern Mono": "Linux",
  "Tsukushi A Round Gothic": "Mac OS",
  "Verdana Gras Italique": "Mac OS",
  "TG Termes Math": "Linux",
  "Latin Modern Mono Light Cond": "Linux",
  "Coronet": "Windows",
  "Klee": "Mac OS",
  "Bodoni 72 Oldstyle": "Mac OS",
  "Arial Narrow Gras": "Mac OS",
  "Police système Intense": "Mac OS",
  "Trebuchet MS Gras": "Mac OS",
  "MotoyaG04GothicMono": "Chrome OS",
  "Ume Gothic C4": "Linux",
  "Cataneo BT": "Windows",
  "Rage Italic LET": "Windows",
  "Latin Modern Roman Slanted": "Linux",
  "URW Gothic": "Linux"
};

module.exports = dataFonts;

